'use client'

import { ArrowRight } from 'lucide-react'
import Link from 'next/link'
import { useScrollReveal, useCountUp } from '@/hooks/useScrollAnimations'

export default function ScoreDimensions() {
  const { ref: sectionRef, isVisible: sectionVisible } = useScrollReveal(0.1)
  const { ref: scoreRef, isVisible: scoreVisible } = useScrollReveal(0.3)
  const scoreValue = useCountUp(84, 2000, scoreVisible)
  const { ref: leftRef, isVisible: leftVisible } = useScrollReveal(0.2)
  const { ref: rightRef, isVisible: rightVisible } = useScrollReveal(0.2)

  return (
    <section
      ref={sectionRef}
      className="relative bg-[#04060D] text-white py-32 overflow-hidden border-t border-white/5"
      style={{
        opacity: sectionVisible ? 1 : 0,
        transform: sectionVisible ? 'scale(1)' : 'scale(0.97)',
        transition: 'opacity 0.8s cubic-bezier(0.16, 1, 0.3, 1), transform 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
      }}
    >
      
      <div className="absolute bottom-0 right-0 w-[800px] h-[600px] bg-[#7B61FF]/5 blur-[150px] rounded-full pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center">
          
          {/* Left Visual — Board Report Mockup */}
          <div
            ref={leftRef}
            className="order-2 lg:order-1 relative"
            style={{
              opacity: leftVisible ? 1 : 0,
              transform: leftVisible ? 'translateX(0)' : 'translateX(-60px)',
              transition: 'opacity 0.9s cubic-bezier(0.16, 1, 0.3, 1), transform 0.9s cubic-bezier(0.16, 1, 0.3, 1)',
            }}
          >
            <div ref={scoreRef} className="relative">
              {/* Board Report Card */}
              <div className="w-full aspect-[4/3] rounded-2xl bg-white relative overflow-hidden transform -rotate-2 hover:rotate-0 transition-transform duration-700 shadow-2xl shadow-[#7B61FF]/10 cursor-default">
                
                {/* Card inner padding */}
                <div className="absolute inset-0 flex flex-col p-6 sm:p-8">
                  
                  {/* Header */}
                  <div className="flex items-center justify-between mb-auto">
                    <div className="flex items-center gap-3">
                      {/* VeloDesk gradient logo square */}
                      <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-lg bg-gradient-to-br from-[#7B61FF] via-[#5B8DEF] to-[#38BDF8] flex items-center justify-center shadow-md">
                        <span className="text-white font-bold text-xs sm:text-sm tracking-tighter">V</span>
                      </div>
                      <div>
                        <div className="text-[10px] sm:text-xs font-mono font-semibold text-gray-800 tracking-widest uppercase">Q3 Board Update</div>
                        <div className="text-[9px] sm:text-[10px] font-mono text-gray-400">October 2026</div>
                      </div>
                    </div>
                    <div className="flex gap-1">
                      <div className="w-2 h-2 rounded-full bg-gray-200" />
                      <div className="w-2 h-2 rounded-full bg-gray-200" />
                      <div className="w-2 h-2 rounded-full bg-gray-200" />
                    </div>
                  </div>

                  {/* Center — Score */}
                  <div className="flex-1 flex flex-col items-center justify-center gap-2">
                    <div className="text-[10px] sm:text-xs font-mono font-semibold text-gray-400 tracking-[0.2em] uppercase">Certified PMF Score</div>
                    
                    {/* Large animated counter */}
                    <div className="text-6xl sm:text-8xl font-light tracking-tighter bg-gradient-to-r from-[#7B61FF] via-[#5B8DEF] to-[#38BDF8] bg-clip-text text-transparent leading-none">
                      {scoreValue}
                    </div>
                    
                    {/* Gradient divider bar */}
                    <div className="w-32 sm:w-48 h-1 rounded-full bg-gradient-to-r from-[#7B61FF] via-[#5B8DEF] to-[#38BDF8] mt-2 opacity-80" />
                    
                    <div className="text-[9px] sm:text-[10px] font-mono text-gray-300 mt-1">
                      Top 4% of Series A cohort
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="flex items-center justify-between mt-auto pt-3 border-t border-gray-100">
                    <span className="text-[8px] sm:text-[9px] font-mono text-gray-300 tracking-[0.15em] uppercase">Confidential</span>
                    <span className="text-[8px] sm:text-[9px] font-mono text-gray-300 tracking-wider">Generated by <span className="font-semibold text-gray-400">VELODESK</span></span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Text — slides in from right */}
          <div
            ref={rightRef}
            className="order-1 lg:order-2"
            style={{
              opacity: rightVisible ? 1 : 0,
              transform: rightVisible ? 'translateX(0)' : 'translateX(60px)',
              transition: 'opacity 0.9s cubic-bezier(0.16, 1, 0.3, 1) 0.15s, transform 0.9s cubic-bezier(0.16, 1, 0.3, 1) 0.15s',
            }}
          >
            <h2 className="text-4xl md:text-5xl font-medium tracking-tight leading-[1.1] mb-6">
              <span className="bg-gradient-to-b from-white to-white/60 bg-clip-text text-transparent">The only slide your board</span><br />
              <span className="font-['Instrument_Serif'] italic bg-gradient-to-r from-[#7B61FF] via-[#5B8DEF] to-[#38BDF8] bg-clip-text text-transparent">actually wants to see.</span>
            </h2>
            <p className="text-lg text-white/40 font-light leading-relaxed mb-10">
              Stop spending 40 hours a month pasting charts into PowerPoint. With one click, VeloDesk exports your certified PMF Score and underlying telemetry into a stunning, board-ready pitch deck.
            </p>

            <Link href="/auth/register" className="inline-flex items-center gap-3 bg-gradient-to-r from-[#7B61FF] to-[#38BDF8] bg-clip-text text-transparent font-medium hover:brightness-125 transition group">
              See a sample Board Report 
              <ArrowRight size={18} className="text-[#7B61FF] transform group-hover:translate-x-1 transition" />
            </Link>
          </div>

        </div>

      </div>
    </section>
  )
}
